{
 "title": "Activities",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Activities Timeline",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(timetrack_activities_counter[$__range])) by (context, category)",
     "legendFormat": "{{context}} {{category}}"
    }
   ]
  },
  {
   "title": "Activities Counter",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "timetrack_activities_counter", "legendFormat": "{{context}}: {{category}}" }
   ]
  },
  {
   "title": "Activities Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "timetrack_activities_duration", "legendFormat": "{{quantile}} {{category}}" }
   ]
  }
 ]
}